folio-org/folio-query-tool-metadata

src/main/resources/swagger.api/schemas/entityTypeColumn.json

Add "visibleByDefault" boolean property to entity type's column definition schema. This new property will indicate if the column has to be shown by default when the entity is displayed to a user (for example, via the viewer component)
Add the property to "enitityTypeColumn.json" file
None
N/A

US1066076: Add 'visibleByDefault' field to entityTypeColumn schema

---

pom.xml
src/main/resources/swagger.api/queryTool.yaml
src/main/resources/swagger.api/schemas/entityDataType.json

The data type names for column definitions were very long, having the format 'XYZEntityDataType" (example: StringEntityDataType). Purpose of this change is to shorten the data type names by removing the word "EntityData" from the data type name. For example shorten "StringEntityDataType" to "StringType"
Here is an example definition based on the updated schema
`
{
"id": "123",
"name": "item_details",
"columns": [
{
"name": "pk-string-col",
"labelAlias": "pk-string-col-label",
"dataType": {
"dataType": "stringType"
}
},
{
"name": "pk-int-col1",
"labelAlias": "pk-int-col-label",
"dataType": {
"dataType": "integerType"
}
}
]
}
`
Made the changes as explained in the "Purpose" section. Executed "mvn compile" and ensured that DTO classes are created successfully. Deserialized a sample …

US1067196: Make data types less verbose by removing the word 'EntityData'

---

pom.xml
src/main/resources/swagger.api/queryTool.yaml
src/main/resources/swagger.api/schemas/entityType.json
src/main/resources/swagger.api/schemas/entityTypeDefaultSort.json

Each entity type should have a default sort criteria. The default sort criteria specifies the columns & the direction based on which the records in an entity type will be sorted by default. 
Purpose of this pull request is to update the "entityType.json" schema by including the "defaultSort" configuration.
Update the "entityType.json" schema by including the "defaultSort" configuration.
None
N/A

US1074823: Enhance entityType schema by adding 'defaultSort' meta-data

---

pom.xml
src/main/resources/swagger.api/examples/columnValues.sample
src/main/resources/swagger.api/examples/totalRecords.sample
src/main/resources/swagger.api/queryTool.yaml
src/main/resources/swagger.api/schemas/columnValueGetter.json
src/main/resources/swagger.api/schemas/columnValues.json
src/main/resources/swagger.api/schemas/entityType.json
src/main/resources/swagger.api/schemas/entityTypeColumn.json
src/main/resources/swagger.api/schemas/resultset.json
src/main/resources/swagger.api/schemas/sourceColumn.json

1. Define a new API to fetch records count for an FQL query
2. Define a new API to fetch the possible values in an entity type column
3. Add "idColumnName", "source" and "valueGetter" fields to column definition
4. Add "entityTypeId" query parameter to "/query" API
None
N/A

US1084584: Add GET recordsCount & columnValue API; Enhance column Defintion with new fields

---

src/main/resources/swagger.api/schemas/columnValues.json
src/main/resources/swagger.api/schemas/entityType.json

Add 'private' and 'subEntityTypeIds' fields to EntityType definition schema
Add 'private' and 'subEntityTypeIds' fields to EntityType definition schema
None
N/A

US1112198: Add 'private' and 'subEntityTypeIds' fields to EntityType definition schema

---

pom.xml
src/main/resources/swagger.api/queryTool.yaml
src/main/resources/swagger.api/schemas/query.json

[US1151239](https://rally1.rallydev.com/#/?detail=/userstory/719697203519&fdp=true): mod-list-app: Use the FQM API instead of going to its DB schema
Implementation of above ticket requires new APIs to be defined in this repository.
2 new APIs were defined to make this possible. 
- GET /query/{queryId}/sortedIds - This API is used to get the ids for a query in sorted order. This is needed because mod-lists can't access the underlying views directly since they are in mod-fqm-manager.
- GET /query/contents - This API is used to get the full result set for a list of ids. This is needed because mod-lists only stores an element's id and sort sequence in the list contents table. The actual content for the ids needs to be retrieved from the views in mod-fqm-manager. But since mod-lists isn't …

US1151239: Use the FQM API instead of going to its DB schema

---

src/main/resources/swagger.api/queryTool.yaml
src/main/resources/swagger.api/schemas/columnValues.json
src/main/resources/swagger.api/schemas/entityType.json
src/main/resources/swagger.api/schemas/entityTypeColumn.json
src/main/resources/swagger.api/schemas/error/error.json
src/main/resources/swagger.api/schemas/error/errors.json
src/main/resources/swagger.api/schemas/error/parameters.json
src/main/resources/swagger.api/schemas/query.json
src/main/resources/swagger.api/schemas/resultset.json
src/main/resources/swagger.api/schemas/sourceColumn.json

[Fix api-lint errors with the examples](https://issues.folio.org/browse/FQTM-4)
- Note: there are still 2 warnings that occur during compilation due to the use of the `allOf` parameter. However, these have always been present and don't seem to be causing any problems so it may be ok to leave it for now.

FQTM-4: Fix api-lint errors with the examples

---

src/main/resources/swagger.api/schemas/entityType.json

Add optional groupByFields to entity type definition. This field can be used for queries that need a group by clause, such as those for array fields.

Add optional groupByFields to entity type definition

---

pom.xml
src/main/resources/swagger.api/queryTool.yaml
src/main/resources/swagger.api/schemas/entityDataType.json

Some fields, such as purchase order lines' fund distributions, are arrays of objects. To enable better display and querying of these fields, we need to store metadata about these nested properties (data types, labels, etc).

[MODFQMMGR-150] Add nested object types

---

src/main/resources/swagger.api/schemas/entityDataType.json
src/main/resources/swagger.api/schemas/field.json

Left this out of #42 ; we want this fully qualified label for use in the query builder and when selecting columns in the result viewer.
For example, fund distributions:
- Parent `fund_distributions` column: `labelAlias=Fund distribution`
- Child `amount` property: `labelAlias=Amount` (for showing within results)
- Child `amount` property: `labelAliasFullyQualified=Fund distribution — amount` or `Fund distribution amount`, etc.

[FQTM-6] Add fully qualified nested property label

---

pom.xml

Update `openapi-generator` to v7.3.0. We need at least v7.0.0 due to the (for us) breaking change in v6.5.0, which erroneously added a `@deprecated` annotation to the default no-args constructor, breaking our javadoc compilation and thus our builds. See https://github.com/OpenAPITools/openapi-generator/issues/15478 for more details.

[FQTM-7] Use openapi-generator v7.3.0

---

src/main/resources/swagger.api/schemas/entityTypeColumn.json
src/main/resources/swagger.api/schemas/field.json

`idColumnName` should apply to `Field`, since theoretically there's no reason we couldn't have nested properties with the same kind of id column mapping logic.

[LIBFQMQUER-12] Generalize idColumnName to Field intead of EntityTypeColumn

---

src/main/resources/swagger.api/schemas/entityType.json

This will allow us to specify what permissions are required for specific entity types, in addition to the very broad FQM API permissions

MODFQMMGR-268 Add required permissions to EntityType

---

src/main/resources/swagger.api/schemas/entityType.json

This will allow us to deal with entity types without columns fairly easily in mod-fqm-manager, rather than having to constantly check to see if it's null

MODFQMMGR-313 Add a default for entity type columns

---

src/main/resources/swagger.api/schemas/entityDataType.json

MODFQMMGR-308:Keep UUID fields as UUIDs to take advantage of indexes

---

pom.xml
src/main/resources/swagger.api/schemas/entityType.json
src/main/resources/swagger.api/schemas/sourceColumn.json

This commit adds a new boolean crossTenantQueriesEnabled property to entity types, to control when an entity type supports cross-query queries. It also changes the shape of the entity type column "source" property's object model, adding a new "type" property. This new property will allow us to use the "source" to define value sources that come from things besides entity types. There's also a new "name" property, which is for setting the name of the value provider within the source type

MODFQMMGR-378 Update approach to enabling ECS for an entity type

---

src/main/resources/swagger.api/schemas/query.json

Add crossTenant property to QueryDetails

Add crossTenant property to QueryDetails

---

pom.xml
src/main/resources/swagger.api/queryTool.yaml
src/main/resources/swagger.api/schemas/fqmMigrateRequest.json
src/main/resources/swagger.api/schemas/fqmMigrateResponse.json
src/main/resources/swagger.api/schemas/fqmMigrateWarning.json

This moves the schemas for migration requests/responses out of `mod-fqm-manager` to facilitate easy sharing between `mod-fqm-manager` and `mod-lists`

[MODLISTS-129] Move migration request/response types from mod-fqm-manager

---

pom.xml

This commit upgrades us from spring-boot-starter-parent v3.2.2 to v3.3.5, in order to move away from a few vulnerable dependencies

FQTM-10 Bump to spring-boot starter 3.3.5

---

src/main/resources/swagger.api/queryTool.yaml

Reverts folio-org/folio-query-tool-metadata#79

Revert "MODFQMMGR-635:Add Query Parameter to /entity-types Endpoint to Retrie…"

---

pom.xml
src/main/resources/swagger.api/queryTool.yaml
src/main/resources/swagger.api/schemas/entityType.json
src/main/resources/swagger.api/schemas/entityTypeColumn.json
src/main/resources/swagger.api/schemas/entityTypeSource.json
src/main/resources/swagger.api/schemas/entityTypeSourceDatabase.json
src/main/resources/swagger.api/schemas/entityTypeSourceDatabaseJoin.json
src/main/resources/swagger.api/schemas/entityTypeSourceEntityType.json
src/main/resources/swagger.api/schemas/field-joins/join.json
src/main/resources/swagger.api/schemas/field-joins/joinCustom.json
src/main/resources/swagger.api/schemas/field-joins/joinDirection.json
src/main/resources/swagger.api/schemas/field-joins/joinEqualityCastUUID.json
src/main/resources/swagger.api/schemas/field-joins/joinEqualitySimple.json

This PR creates a new join model which reinforces the idea of simple entity types each representing 1 DB source being joined together in arbitrary ways by higher-order entity types. This is accomplished by using a new set of pre-defined join types as part of column definitions themselves, _enabling entity types to know how to join with each other, rather than requiring higher-order entities to explicitly specify raw SQL every time_.
Column definitions will now describe what other columns they can join to. For example, in the user's entity type:
```json5
{
name: 'group_id',
sourceAlias: 'user',
dataType: {
dataType: 'rangedUUIDType',
},
isIdColumn: false,
queryable: true,
visibleByDefault: false,
valueGetter: ":sourceAlias.jsonb->>'patronGroup'",
joinsTo: [
{
targetId: …
```

[FQTM-11] New entity type join model

---

NEWS.md
pom.xml
src/main/resources/swagger.api/queryTool.yaml
src/main/resources/swagger.api/schemas/entityType.json

This property is unused. This is a breaking change, so this commit also does a major version bump on the library

MODFQMMGR-780 Remove the "root" ET property

---

pom.xml
src/main/resources/swagger.api/queryTool.yaml
src/main/resources/swagger.api/schemas/entityDataType.json
src/main/resources/swagger.api/schemas/entityTypeSourceEntityType.json

Add new properties required for [MODFQMMGR-653](https://folio-org.atlassian.net/browse/MODFQMMGR-653) (custom field metadata + `inheritCustomFields` property for EntityTypeSources)
Here's an example of how a custom field column will look after these changes:
```
{
"name": "user_custom_fields", // encompasses all custom fields defined in the src_user_custom_fields view
"essential": true,
"queryable": true,
"visibleByDefault": false,
"dataType": {
"dataType": "customFieldType",
"customFieldMetadata": {
"configurationView": "src_user_custom_fields",
"dataExtractionPath": ":user.jsonb -> 'customFields'"
}
}
}
```

Refactor FQM's approach to custom field configuration in entity types
