pom.xml
src/main/resources/swagger.api/examples/entityTypeDefinition.sample
src/main/resources/swagger.api/queryTool.yaml
src/main/resources/swagger.api/schemas/error/error.json
src/main/resources/swagger.api/schemas/error/errors.json
src/main/resources/swagger.api/schemas/error/parameter.json
src/main/resources/swagger.api/schemas/error/parameters.json

Define GET /entity-types/{id} API in folio-query-tool-metadata
Add API definition to queryTool.yaml file
None
N/A

US1071443:  Define GET /entity-types/{id} API

---

src/main/resources/swagger.api/queryTool.yaml

Enhance GET /entity-types/{id}/columns/{name}/values API to accept 'search' query parameter
Update the Open API definition.
None
N/A

US1087153: Enhance GET /entity-types/{id}/columns/{name}/values API to accept 'search' query parameter

---

pom.xml
src/main/resources/swagger.api/examples/queryDetails.sample
src/main/resources/swagger.api/queryTool.yaml
src/main/resources/swagger.api/schemas/query.json

Defile new APIs needed to fetch the status & contents of a submitted query asynchronously
Defile new APIs needed to fetch the status & contents of a submitted query asynchronously
None 
N/A

US1093544: New APIs needed to fetch the status & contents of a submitted query asynchronously

---

src/main/resources/swagger.api/schemas/query.json

Add queryId and fqlQuery to Query object
Add queryId and fqlQuery to Query object
None
N/A

US1094353: Add queryId and fqlQuery to Query object

---

src/main/resources/swagger.api/schemas/query.json

Add CANCELLED status for Query
Add CANCELLED status for Query
None
N/A

US1094414: Add CANCELLED status for Query

---

pom.xml

US1120486: Make spring an optional dependency

---

.github/workflows/api-doc.yml
.github/workflows/api-lint.yml
.github/workflows/api-schema-lint.yml
Jenkinsfile
src/main/resources/swagger.api/queryTool.yaml

[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).

FOLIO-3678 FQTM-3 Use GitHub Workflows api-lint and api-schema-lint and api-doc

---

src/main/resources/swagger.api/queryTool.yaml
src/main/resources/swagger.api/schemas/common.json
src/main/resources/swagger.api/schemas/entityDataType.json
src/main/resources/swagger.api/schemas/entityTypeColumn.json
src/main/resources/swagger.api/schemas/entityTypeRelation.json
src/main/resources/swagger.api/schemas/query.json
src/main/resources/swagger.api/schemas/resultset.json

[US1143863](https://rally1.rallydev.com/#/?detail=/userstory/715105800747&fdp=true): Update query definition to include field projection
This ticket also resolves some linting errors by where needed.

US1143863: Update query definition to include field projection

---

src/main/resources/swagger.api/schemas/query.json

Add sortResults param to submitQuery

Add sortResults param to submitQuery

---

src/main/resources/swagger.api/schemas/entityType.json

 MODFQMMGR-99: fixing the type

---

src/main/resources/swagger.api/schemas/entityTypeColumn.json

Adding a field to the column to indicate whether its a custom column or not

MODFQMMGR-99: adding field to indicate whether its a custom column

---

pom.xml
src/main/resources/swagger.api/schemas/entityTypeColumn.json
src/main/resources/swagger.api/schemas/valueSourceApi.json

This new property will allow us to configure an API endpoint as the source of available values for a column

MODFQMMGR-134 Add a value source API property for columns

---

NEWS.md
pom.xml

Prepare release v1.1.0

---

src/main/resources/swagger.api/schemas/query.json

[MODFQMMGR-137](https://folio-org.atlassian.net/browse/MODFQMMGR-137): Change query result id from UUID to string array

MODFQMMGR-137: Change query result id from UUID to string array

---

src/main/resources/swagger.api/queryTool.yaml
src/main/resources/swagger.api/schemas/entityTypeColumn.json

[MODFQMMGR-137](https://folio-org.atlassian.net/browse/MODFQMMGR-137): Update APIs to use list of strings as result ids

MODFQMMGR-137: Update APIs to use list of strings as result ids

---

src/main/resources/swagger.api/schemas/entityDataType.json

Seems this was accidentally removed in #42...

[FQTM-6] Re-add incorrectly removed column from object properties

---

src/main/resources/swagger.api/schemas/field.json

Not all fields need to be, nor should be, queryable.

[MODFQMMGR-141] Add queryable flag for entity type columns

---

src/main/resources/swagger.api/schemas/query.json

Add field to SubmitQuery json to set limit on max query size

MODFQMMGR-172: Set limit on max number of query results

---

pom.xml
src/main/resources/swagger.api/schemas/entityType.json
src/main/resources/swagger.api/schemas/entityTypeSource.json
src/main/resources/swagger.api/schemas/entityTypeSourceJoin.json
src/main/resources/swagger.api/schemas/field.json

Tentative object model for POC

MODFQMMGR-229: POC Object Model

---

pom.xml

adding-to-pom: adding StringUUIDType to pom file

---

pom.xml

fixing-typo: from S to s

---

src/main/resources/swagger.api/queryTool.yaml

adding-to-yaml: adding stringUUIDType to yaml

---

src/main/resources/swagger.api/schemas/field.json

Add ecsOnly property to EntityTypeColumn definition

Add ecsOnly property to field definition

---

src/main/resources/swagger.api/schemas/entityType.json

Add additionalEcsConditions property to entity type definition

Add additionalEcsConditions property to entity type definition

---

src/main/resources/swagger.api/schemas/query.json

[MODFQMMGR-481](https://folio-org.atlassian.net/browse/MODFQMMGR-481): Add localize parameter to GET /query/contents endpoint

MODFQMMGR-481: Add localize parameter to GET contents endpoint

---

src/main/resources/swagger.api/queryTool.yaml
src/main/resources/swagger.api/schemas/query.json

Add /query/contents/privileged endpoint for use by mod-lists during exports

Add /query/contents/privileged endpoint

---

Jenkinsfile
pom.xml

Reverts folio-org/folio-query-tool-metadata#87

Revert "[FOLIO-4235] Update Java to v21"

---

src/main/resources/swagger.api/schemas/customEntityType.json

Owner is a bit more flexible and makes more sense with how it's used

MODFQMMGR-632 Change custom ET creator property to owner

---

src/main/resources/swagger.api/schemas/entityType.json

[MODFQMMGR-788](https://folio-org.atlassian.net/browse/MODFQMMGR-788): Add support for entity-type-level filters

[MODFQMMGR-788] Add support for entity-type-level filters

---

src/main/resources/swagger.api/schemas/entityDataType.json

[https://folio-org.atlassian.net/browse/MODFQMMGR-918](https://folio-org.atlassian.net/browse/MODFQMMGR-918): Split handling for DateTypes and DateTimeTypes

[MODFQMMGR-918] Split handling for DateTypes and DateTimeTypes
